#Alfredo Moreira
#Put this file in a .circleci/ folder
#This file is to be used to run Github Status Checks
version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.3
jobs: 
  build:
    docker:
      - image: circleci/node:15.6.0
    working_directory: ~/catalog-api
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Check Node Version
          command: node --version
      - run:
          name: Install Packages
          command: npm install
      #save cache for use next tests
      - save_cache:
         paths:
          - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}
      #Recreate .env file from CircleCI Project Env Vars
      - run:
          name: Create .env file
          command: |
           cat \<< EOF > ./.env
           MAILGUN_API_KEY=$MAILGUN_API_KEY
           MAILGUN_DOMAIN=$MAILGUN_DOMAIN
           DB_URI=$DB_URI
           SHEETS_API_KEY=$SHEETS_API_KEY
           EOF

      #Building and Compiling Binary
      - run: 
          name: Compile Binary
          command: npm run build
  e2e:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/catalog-api
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Check Node Version
          command: node --version
      - run:
          name: Install Packages
          command: npm install
      #save cache for use next tests
      - save_cache:
         paths:
          - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}
      #Recreate .env file from CircleCI Project Env Vars
      - run:
          name: Create .env file
          command: |
           cat \<< EOF > ./.env
           MAILGUN_API_KEY=$MAILGUN_API_KEY
           MAILGUN_DOMAIN=$MAILGUN_DOMAIN
           DB_URI=$DB_URI
           SHEETS_API_KEY=$SHEETS_API_KEY
           EOF
      #Start Server
      - run: 
          name: "Start Server"
          command: "npm run pre-test" 
      #Running E2E Tests
      - run: 
          name: End2End Testing
          command: npm run e2e-circle
      - codecov/upload:
          file: 'coverage/coverage-final.json'
          flags: 'Integration'
      - store_artifacts:
          path: "reports/e2e-report.hml"


workflows:
  version: 1
  pull_request:
    jobs:
      - build
      - e2e